#!/usr/bin/env php
<?php
namespace zxq;

class RunApi
{
    public static function run()
    {
        // 定义项目路径
        define('APP_PATH', __DIR__ . '/src/');
        require __DIR__ . './src/thinkphp/base.php';

        \think\App::initCommon();
        \think\Console::init();
    }
}